import { Run, offers, LENGTH, FORK, sectionAt, validateContent, type Offer } from './model';
import riverLayout from './river-layout.json';

const $ = <T extends HTMLElement=HTMLElement>(id:string)=>document.getElementById(id) as T;
const canvas=$<HTMLCanvasElement>('river'),ctx=canvas.getContext('2d')!;
let W=innerWidth,H=innerHeight,scale=1,time=0,last=0,run=new Run();
type Mode='menu'|'playing'|'dialog'|'paused'|'results'|'recovery';
let mode:Mode='menu',resumeMode:Mode='playing',dialogOffer:Offer|null=null,dialogTarget=false,recoveryTime=0,toastTime=0,muted=true,audio:AudioContext|null=null,nextMusic=0;
const keys=new Set<string>();
let pointerX:number|null=null;
let hoverPointer:{x:number;y:number}|null=null;
let paceHovered=false;
let mousePace=0;
let selectedDock:{id:string;target:boolean}|null=null;
function resetPointer(){pointerX=null;hoverPointer=null;mousePace=0;selectedDock=null;updatePace()}
function updatePace(){for(const [id,pace] of [['pace-slow',-1],['pace-cruise',0],['pace-fast',1]] as const)$(id).setAttribute('aria-pressed',String(mousePace===pace))}
for(const [id,pace] of [['pace-slow',-1],['pace-cruise',0],['pace-fast',1]] as const)$(id).onclick=()=>{mousePace=pace;updatePace()};
canvas.addEventListener('pointermove',e=>{if(mode!=='playing'||e.pointerType==='touch')return;pointerX=e.clientX;hoverPointer={x:e.clientX,y:e.clientY};selectedDock=null});
canvas.addEventListener('pointerleave',()=>{hoverPointer=null;if(!selectedDock)pointerX=null});
document.querySelector('.pace-controls')!.addEventListener('pointerenter',()=>{paceHovered=true});
document.querySelector('.pace-controls')!.addEventListener('pointerleave',()=>{paceHovered=false});
function dockAtPointer(x:number,y:number){return availableDocks().find(n=>{
 const side=n.target&&n.offer.branch?n.offer.branch:n.offer.side;
 const cx=sx(dockX(n.offer,n.target),n.d)+side*26*scale;
 const cy=sy(n.d)-20*scale;
 return n.d>=run.distance-115&&((x-cx)/(55*scale))**2+((y-cy)/(65*scale))**2<=1;
})}
canvas.addEventListener('click',e=>{
 if(mode!=='playing')return;
 const dock=dockAtPointer(e.clientX,e.clientY);
 if(dock){
  if(dock.d<run.distance-115){toast('That landing is behind us. More friends ahead!');return}
  selectedDock={id:dock.offer.id,target:dock.target};
  toast(`Heading to ${dock.target?dock.offer.recipient:dock.offer.name}. Move the mouse to cancel.`);
  if(nearDock())interact();return;
 }
 const lost=run.active.find(t=>t.offer.type==='lost'&&Math.hypot(e.clientX-sx(Math.sin(t.offer.target)*100,t.offer.target),e.clientY-sy(t.offer.target))<Math.max(32,35*scale));
 if(lost){if(nearLost()===lost)interact();else toast('Move closer to the floating item, then click it.');return}
 pointerX=e.clientX;selectedDock=null;
});
const used=new Set<string>();
const floaters:{x:number;d:number;text:string;life:number}[]=[];
let sectionHits=0,lastClean=0;
const icons={parcel:'📦',lost:'✦',rescue:'♥',collection:'●'};
interface Entity {id:string;d:number;x:number;type:'rock'|'log'|'branch'|'berry'|'bamboo'}
const entities=riverLayout as Entity[];

function resize(){W=innerWidth;H=innerHeight;const dpr=Math.min(devicePixelRatio,2);canvas.width=W*dpr;canvas.height=H*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);scale=Math.min(W/1100,H/760);}
addEventListener('resize',resize);resize();
function savedBest(){try{return Number(localStorage.getItem('red-panda-best')||0)}catch{return 0}}
function displayBest(){ $('best').textContent=savedBest()?`YOUR RIVER RECORD  ·  ${savedBest().toLocaleString()} POINTS`:'' }
displayBest();
function show(id:string,visible:boolean){$(id).hidden=!visible}
function toast(text:string){$('toast').textContent=text;show('toast',true);toastTime=5}
function initAudio(){if(!audio)audio=new AudioContext();void audio.resume()}
function tone(freq:number,duration=.15,volume=.035,type:OscillatorType='sine'){
 if(muted||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration);
}
let ambience:AudioBufferSourceNode|null=null,ambienceGain:GainNode|null=null;
function soundToggle(){muted=!muted;initAudio();if(!ambience&&audio){const buffer=audio.createBuffer(1,audio.sampleRate*3,audio.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.sin(i*37.13)+Math.sin(i*17.73))*.25;ambience=audio.createBufferSource();ambience.buffer=buffer;ambience.loop=true;const filter=audio.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;ambienceGain=audio.createGain();ambience.connect(filter).connect(ambienceGain).connect(audio.destination);ambience.start()}if(ambienceGain)ambienceGain.gain.value=muted?0:.045;$('sound').innerHTML=`♪ <span>SOUND ${muted?'OFF':'ON'}</span>`;$('sound').setAttribute('aria-label',muted?'Unmute sound':'Mute sound');tone(440)}
$('sound').onclick=soundToggle;
function start(){resetPointer();run=new Run();used.clear();floaters.length=0;sectionHits=0;lastClean=0;keys.clear();mode='playing';for(const id of ['menu','results','pause','dialog'])show(id,false);show('hud',true);toast('Move your mouse to steer. Click an animal to pull over. Arrow keys work too!');initAudio();updateHUD()}
function home(){resetPointer();mode='menu';keys.clear();for(const id of ['hud','results','pause','dialog','prompt','toast'])show(id,false);show('menu',true);displayBest()}
function pause(){if(mode==='playing'||mode==='dialog'||mode==='recovery'){resumeMode=mode;mode='paused';keys.clear();resetPointer();show('pause',true)}else if(mode==='paused'){mode=resumeMode;show('pause',false)}}
$('play').onclick=start;$('again').onclick=start;$('home').onclick=home;$('quit').onclick=home;$('resume').onclick=pause;$('pause-button').onclick=pause;
function finish(){mode='results';run.active=[];show('hud',false);show('prompt',false);show('results',true);const previous=savedBest();try{localStorage.setItem('red-panda-best',String(Math.max(previous,run.score)))}catch{/* Storage is optional. */}$('final-score').textContent=run.score.toLocaleString();$('stats').innerHTML=[['River score',run.riverScore],['Task score',run.taskScore],['Tasks completed',run.completed],['Critters helped',run.helped],['Berries gathered',run.berries],['Longest streak',run.longest],['Collisions',run.collisions],['Recovery penalties',`−${run.penalties}`]].map(([a,b])=>`<div>${a}<strong>${b}</strong></div>`).join('');$('result-best').textContent=run.score>previous?'A NEW PERSONAL BEST!':`PERSONAL BEST · ${previous.toLocaleString()}`;tone(660,.5)}
function riverCenter(d:number){return Math.sin(d/1800)*42+Math.sin(d/670)*14}
function halfWidth(d:number){return d>17000&&d<25500?218+Math.sin(d/600)*25:280+Math.sin(d/1100)*22}
function forkSize(d:number){if(d<FORK.start||d>FORK.end)return 0;return Math.min(1,(d-FORK.start)/800,(FORK.end-d)/800)*83}
function centerScreen(){return mode==='menu'?W*.70:W*.50}
function viewDistance(){return mode==='menu'?2800:run.distance}
function sy(d:number){return H*.65-(d-viewDistance())*scale}
function sx(x:number,d:number){return centerScreen()+(riverCenter(d)+x)*scale}
function entityX(e:Entity){const island=forkSize(e.d);return island>0?Math.sign(e.x||1)*(island+37+Math.abs(e.x)*(halfWidth(e.d)-island-75)):e.x*(halfWidth(e.d)-35)}
function dockX(o:Offer,target=false){return (target&&o.branch?o.branch:o.side)*(halfWidth(target?o.target:o.at)-18)}
function availableDocks(){return offers.flatMap(o=>{const active=run.active.some(t=>t.offer.id===o.id);return [...(!run.resolved.has(o.id)&&run.distance<o.at+200?[{offer:o,target:false,d:o.at}]:[]),...(active&&o.type!=='lost'?[{offer:o,target:true,d:o.target}]:[])]})}
function nearDock(){return availableDocks().find(n=>(!selectedDock||(n.offer.id===selectedDock.id&&n.target===selectedDock.target))&&Math.abs(n.d-run.distance)<115&&Math.abs(run.x-dockX(n.offer,n.target))<90)}
function nearLost(){return run.active.find(t=>t.offer.type==='lost'&&Math.abs(t.offer.target-run.distance)<85&&Math.abs(run.x-Math.sin(t.offer.target)*100)<85)}
function interact(){if(mode!=='playing')return;const lost=nearLost();if(lost){const points=run.complete(lost.offer.id);toast(`${lost.offer.item} rescued! +${points}`);tone(784,.3);return}const dock=nearDock();if(!dock)return;dialogOffer=dock.offer;dialogTarget=dock.target;resetPointer();mode='dialog';keys.clear();show('prompt',false);const t=run.active.find(t=>t.offer.id===dock.offer.id);const ready=!dock.target||dock.offer.type!=='collection'||(t?.count??0)>=(dock.offer.goal??5);$('dialog-label').textContent=dock.target?'A GOOD DEED COMES ASHORE':'A RIVERBANK FRIEND';$('dialog-title').textContent=dock.target?dock.offer.recipient:dock.offer.name;$('dialog-text').textContent=dock.target?(ready?'You made it! Thank you, little river friend. There’s always a place for you by our campfire.':`The pie needs ${dock.offer.goal} berries. You have ${t?.count??0}. You can gather more nearby, but remember the current only goes downstream.`):dock.offer.dialogue;$('dialog-reward').textContent=dock.target?ready?`Thank you reward · ${Math.round(dock.offer.reward*run.multiplier)} points`:'Come back to the landing when you have enough.':run.active.length===3?'Your raft is full — finish a task to make room.':`${icons[dock.offer.type]} ${dock.offer.item} · ${dock.offer.reward} base points`;$('accept').textContent=dock.target?(ready?'Complete · Enter':'Keep gathering · Enter'):run.active.length===3?'Back to the river · Enter':'Happy to help · Enter';$('decline').textContent=dock.target?'Back to river · Space':'Maybe next time · Space';show('dialog',true);$('accept').focus()}
function closeDialog(accept:boolean){if(mode!=='dialog'||!dialogOffer)return;if(accept){if(dialogTarget){const points=run.complete(dialogOffer.id);if(points){toast(`A little kindness goes a long way. +${points}`);tone(660,.2);setTimeout(()=>tone(880,.3),120)}}else if(run.accept(dialogOffer)){toast(`${dialogOffer.item} · destination marked downstream`);tone(523,.2)}}show('dialog',false);mode='playing';keys.clear();dialogOffer=null;($('accept') as HTMLButtonElement).blur();updateHUD()}
$('accept').onclick=()=>closeDialog(true);$('decline').onclick=()=>closeDialog(false);
addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown',' ','Escape','Enter'].includes(e.key))e.preventDefault();if(e.repeat)return;if(e.key.startsWith('Arrow'))resetPointer();if(e.key==='Escape'){pause();return}if(mode==='dialog'){if(e.key==='Enter')closeDialog(true);else if(e.key===' '||e.key==='Backspace')closeDialog(false);return}if(mode==='menu'&&e.key==='Enter'){start();return}if(mode==='playing'&&e.key===' ')interact();keys.add(e.key)});
addEventListener('keyup',e=>keys.delete(e.key));addEventListener('blur',()=>{keys.clear();if(mode==='playing'||mode==='dialog'||mode==='recovery')pause()});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&(mode==='playing'||mode==='dialog'||mode==='recovery'))pause()});
function updateHUD(){show('boost',run.boostRemaining>0);$('boost').textContent=`BAMBOO BOOST | ${Math.ceil(run.boostRemaining)}s | +50% speed`; $('score').textContent=run.score.toLocaleString();$('section-name').textContent=sectionAt(run.distance);$('hearts').textContent='♥'.repeat(run.hearts)+'♡'.repeat(3-run.hearts);$('hearts').setAttribute('aria-label',`${run.hearts} of 3 hearts`);$('multiplier').textContent=`×${run.multiplier.toFixed(2)} task bonus`;$('task-count').textContent=`${run.active.length} / 3`;$('tasks').innerHTML=run.active.length?run.active.map(t=>`<div class="task">${icons[t.offer.type]} ${t.offer.item}${t.offer.type==='collection'?` ${t.count}/${t.offer.goal}`:''}<small>${t.offer.type==='lost'?'Find it in the river':`→ ${t.offer.recipient}`}${t.offer.branch?' · LEFT FORK':''} · ${Math.max(0,Math.round((t.offer.target-run.distance)/55))}s ahead</small></div>`).join(''):'<p class="empty-task">Watch for a <b>!</b> on shore.<br>A friend could use a hand.</p>';$('progress').style.width=`${100*run.distance/LENGTH}%`;$('journey-label').textContent=`${Math.floor(run.distance/55/60)}:${String(Math.floor(run.distance/55)%60).padStart(2,'0')} / THE TRAIL`}
function update(dt:number){if(toastTime>0){toastTime-=dt;if(toastTime<=0)show('toast',false)}if(mode==='recovery'){recoveryTime-=dt;if(recoveryTime<=0){mode='playing';run.immunity=4;toast('Back afloat! Hearts restored · 150 point maximum recovery penalty')}return}if(mode!=='playing')return;
 const destination=selectedDock?availableDocks().find(n=>n.offer.id===selectedDock!.id&&n.target===selectedDock!.target):undefined;if(selectedDock&&(!destination||destination.d<run.distance-115))selectedDock=null;const docking=!!destination&&destination.d-run.distance<350;
 run.tickBoost(dt);run.immunity=Math.max(0,run.immunity-dt);const speedTarget=((run.distance>17000&&run.distance<25500?65:55)+(keys.has('ArrowUp')||(!docking&&mousePace===1)?24:0)-(keys.has('ArrowDown')||docking||mousePace===-1?30:0))*run.speedMultiplier;run.speed+=(speedTarget-run.speed)*Math.min(1,dt*3);run.distance+=run.speed*dt;
 const aim=destination?dockX(destination.offer,destination.target):pointerX===null?null:(pointerX-centerScreen())/scale-riverCenter(run.distance);const steer=aim===null?(keys.has('ArrowRight')?1:0)-(keys.has('ArrowLeft')?1:0):Math.max(-1,Math.min(1,(aim-run.x)/60));run.vx+=(steer*180-run.vx)*Math.min(1,dt*4);run.x+=run.vx*dt;const bank=halfWidth(run.distance)-24;run.x=Math.max(-bank,Math.min(bank,run.x));
 const island=forkSize(run.distance);if(island>0&&Math.abs(run.x)<island+24){run.x=(run.x<0?-1:1)*(island+24);run.vx=0}if(run.distance>FORK.split&&run.distance<FORK.merge){run.branch=run.x<0?-1:1;if(run.branch===1)run.distance+=10*dt;else run.distance-=5*dt}if(run.distance>FORK.end&&!run.forkAwarded){run.forkAwarded=true;if(run.branch===1){run.addRiver(100);toast('White-water route complete! +100')}else toast('The scenic route. A little longer, a little lovelier.')}
 for(const e of entities){if(used.has(e.id)||Math.abs(e.d-run.distance)>48)continue;const dx=Math.abs(entityX(e)-run.x);if(dx<(e.type==='berry'?36:e.type==='log'?62:36)){if(e.type==='berry'){used.add(e.id);run.berry();floaters.push({x:run.x,d:run.distance,text:'+10',life:1});tone(880,.07,.015)}else if(e.type==='bamboo'){used.add(e.id);run.bamboo();toast('Bamboo boost! 30 seconds of extra speed - click Slow or press Down to brake');floaters.push({x:run.x,d:run.distance,text:'BAMBOO BOOST!',life:2});tone(659,.15,.04);setTimeout(()=>tone(988,.25,.04),100)}else if(!run.immunity){used.add(e.id);sectionHits++;const recovering=run.hit();tone(110,.3,.07,'triangle');floaters.push({x:run.x,d:run.distance,text:'SPLASH!',life:1.5});if(recovering){mode='recovery';recoveryTime=2;run.x=(run.x<0?-1:1)*(halfWidth(run.distance)-30);run.vx=0;toast('A friendly current carries you to a safe bank…')}else toast('Oof! A little splash. Keep paddling.')}}}
 const clean=Math.floor(run.distance/2200);if(clean>lastClean){if(sectionHits===0){run.addRiver(50);floaters.push({x:run.x,d:run.distance,text:'Clean stretch +50',life:2})}lastClean=clean;sectionHits=0}
 const missed=run.miss();if(missed.length)toast(`Passed ${missed.map(t=>t.offer.item).join(', ')}. There are more friends ahead.`);
 if(selectedDock&&nearDock()){interact();updateHUD();return}const dock=nearDock(),lost=nearLost();show('prompt',!!dock||!!lost||(run.distance>9900&&run.distance<11200));$('prompt').textContent=lost?`CLICK or SPACE · Scoop up ${lost.offer.item}`:dock?`CLICK animal or SPACE · Pull over to ${dock.target?dock.offer.recipient:dock.offer.name}`:'FORK AHEAD · ← Calm water & Frog · Rapids +100 →';
 if(keys.has('ArrowUp')&&Math.floor(time*4)!==Math.floor((time-dt)*4))tone(180+Math.sin(time)*30,.06,.008,'triangle');
 if(time>nextMusic){nextMusic=time+.7;const notes=[261.63,329.63,392,523.25,440,392,329.63,293.66];tone(notes[Math.floor(time/.7)%notes.length],.5,.012,'sine')}
 for(const f of floaters)f.life-=dt;while(floaters[0]?.life<=0)floaters.shift();if(run.distance>=LENGTH)finish();updateHUD();
}
function ellipse(x:number,y:number,rx:number,ry:number,color:string){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill()}
function line(x1:number,y1:number,x2:number,y2:number,color:string,width=1){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke()}
function text(str:string,x:number,y:number,size:number,color:string,font='DM Sans'){ctx.fillStyle=color;ctx.font=`600 ${size}px '${font}', sans-serif`;ctx.textAlign='center';ctx.fillText(str,x,y)}
function tree(x:number,y:number,s:number,variant:number){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ellipse(6,17,35,11,'#264f3420');line(0,4,0,-48,'#796044',9);const colors=['#527957','#63885b','#3e7055','#739362'];const c=colors[variant%4];ellipse(-15,-43,24,25,c);ellipse(16,-48,25,29,c);ellipse(0,-68,25,29,c);ellipse(-8,-71,17,18,'#ffffff0c');line(0,-12,13,-34,'#496347',3);ctx.restore()}
function character(x:number,y:number,name:string,s=1){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ellipse(0,15,16,6,'#173b3320');const c=name==='Fox'?'#bb6e3e':name==='Rabbit'?'#dfd7bd':name==='Frog'?'#88a66c':name==='Duck'?'#edd59a':name==='Beaver'?'#947153':'#aaa68b';ellipse(0,3,12,15,c);if(name==='Rabbit'){ellipse(-7,-25,4,15,c);ellipse(7,-25,4,15,c)}else {ellipse(-9,-16,5,6,c);ellipse(9,-16,5,6,c)}ellipse(0,-10,14,12,c);ellipse(0,-6,9,6,'#eee8cf');ellipse(-5,-12,1.5,2,'#243c33');ellipse(5,-12,1.5,2,'#243c33');line(13,0,21,-5+Math.sin(time*3)*5,c,5);ctx.restore()}
function panda(x:number,y:number,s:number){ctx.save();ctx.translate(x,y);ctx.scale(s,s);ctx.rotate(run.vx/1400+(mode==='menu'?-.12:0));const bob=Math.sin(time*2.7)*2;ctx.translate(0,bob);ellipse(0,35,43,51,'#12595528');for(let i=-2;i<=2;i++){ctx.fillStyle=i%2?'#be8c52':'#cfa168';ctx.beginPath();ctx.roundRect(i*15-7,-35,14,86,7);ctx.fill();line(i*15-3,-23,i*15-3,39,'#e7bf80',1)}line(-37,-17,37,-17,'#967048',4);line(-37,32,37,32,'#967048',4);
 ctx.save();ctx.translate(19,11);ctx.rotate(-.6);ellipse(0,12,13,28,'#b95530');for(let i=0;i<4;i++)line(-10,i*10,10,i*10,'#7c422c',5);ctx.restore();ellipse(0,4,21,23,'#8f432b');ellipse(-12,20,9,8,'#493d30');ellipse(12,20,9,8,'#493d30');ellipse(-17,-29,9,11,'#a64b2a');ellipse(17,-29,9,11,'#a64b2a');ellipse(-17,-30,5,6,'#f7dfb3');ellipse(17,-30,5,6,'#f7dfb3');ellipse(0,-14,25,22,'#c66837');ellipse(-14,-10,12,11,'#f5e4bf');ellipse(14,-10,12,11,'#f5e4bf');ellipse(0,-2,10,8,'#f7e7c3');ellipse(-10,-14,3,3,'#30362b');ellipse(10,-14,3,3,'#30362b');ellipse(0,-5,4,3,'#49372b');line(-6,10,15,14,'#648e80',8);ctx.save();ctx.translate(-24,6);ctx.rotate(-.4+(keys.has('ArrowUp')?Math.sin(time*10)*.4:Math.sin(time*2)*.08));line(0,-25,0,46,'#725437',5);ellipse(0,47,9,18,'#d2aa67');ctx.restore();for(const [i,t] of run.active.filter(t=>t.offer.type==='rescue').entries())character(-15+i*24,32,t.offer.item==='Duckling'?'Duck':'Frog',.65);ctx.restore();
 for(let i=0;i<3;i++){const phase=(time*.6+i/3)%1;ctx.globalAlpha=(1-phase)*.35;ctx.strokeStyle='#e2f5de';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(x,y+50*s+phase*40*s,(25+phase*18)*s,8*s,0,0,Math.PI);ctx.stroke()}ctx.globalAlpha=1;
}
function draw(){const hovered=mode==='playing'&&hoverPointer?dockAtPointer(hoverPointer.x,hoverPointer.y):undefined;canvas.style.cursor=hovered?'pointer':mode==='playing'?'crosshair':'default';const pace=document.querySelector<HTMLElement>('.pace-controls')!;pace.hidden=mode!=='playing';if(!paceHovered){pace.style.left=`${Math.round(Math.max(94,Math.min(W-94,sx(run.x,run.distance))))}px`;pace.style.top=`${Math.round(Math.min(H-82,sy(run.distance)+83*scale))}px`;}ctx.clearRect(0,0,W,H);ctx.fillStyle='#c7d3a2';ctx.fillRect(0,0,W,H);const vd=viewDistance();
 // Continuous banks and water, sampled from the same geometry used by collisions.
 const samples:{y:number;d:number;c:number;w:number}[]=[];for(let y=-50;y<H+80;y+=20){const d=vd+(H*.65-y)/scale;samples.push({y,d,c:sx(0,d),w:halfWidth(d)*scale})}
 function riverPath(extra:number){ctx.beginPath();samples.forEach((p,i)=>i?ctx.lineTo(p.c-p.w-extra,p.y):ctx.moveTo(p.c-p.w-extra,p.y));for(const p of [...samples].reverse())ctx.lineTo(p.c+p.w+extra,p.y);ctx.closePath()}
 riverPath(22*scale);ctx.fillStyle='#a6b881';ctx.fill();riverPath(10*scale);ctx.fillStyle='#e2d4a4';ctx.fill();riverPath(0);ctx.fillStyle='#70a99b';ctx.fill();ctx.save();riverPath(0);ctx.clip();const gradient=ctx.createLinearGradient(0,0,W,H);gradient.addColorStop(0,'#99c3aa55');gradient.addColorStop(1,'#285e6630');ctx.fillStyle=gradient;ctx.fillRect(0,0,W,H);
 for(let i=0;i<100;i++){const d=Math.floor(vd/100)*100-800+i*24;const x=Math.sin(i*8.31)*260;const y=sy(d)+(time*11%20);line(sx(x,d),y,sx(x+18+(i%4)*8,d),y-2,'#d3e8c03a',1.5*scale)}
 if(vd>16400&&vd<26000)for(let i=0;i<40;i++){const d=Math.floor(vd/100)*100-500+i*35;const x=Math.sin(i*3)*220;line(sx(x,d),sy(d),sx(x+35,d),sy(d)-8,'#e9f0cf70',3*scale)}
 ctx.restore();
 // Fork island is physical terrain, tapering into and out of the channels.
 ctx.beginPath();let begun=false;for(const p of samples){const f=forkSize(p.d)*scale;if(f>0){if(!begun){ctx.moveTo(p.c-f,p.y);begun=true}else ctx.lineTo(p.c-f,p.y)}}for(const p of [...samples].reverse()){const f=forkSize(p.d)*scale;if(f>0)ctx.lineTo(p.c+f,p.y)}ctx.closePath();ctx.fillStyle='#dfd2a1';ctx.fill();ctx.save();ctx.clip();ctx.fillStyle='#b8ca92';ctx.fillRect(0,0,W,H);ctx.restore();
 for(let i=Math.floor((vd-700)/140);i<Math.ceil((vd+H/scale)/140);i++){const d=i*140;for(const side of [-1,1]){const spread=halfWidth(d)+45+(Math.sin(i*13.1+side)+1)*130;const x=sx(side*spread,d),y=sy(d);tree(x,y,(.8+(Math.sin(i*5)+1)*.25)*scale,Math.abs(i+side));if(i%3===0){ellipse(sx(side*(halfWidth(d)+27),d),y+25,5*scale,3*scale,'#eeedc0');ellipse(sx(side*(halfWidth(d)+32),d),y+17,3*scale,3*scale,'#f7e4ae')}}}
 for(const e of entities){const y=sy(e.d);if(y<-80||y>H+80||used.has(e.id))continue;const x=sx(entityX(e),e.d);ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);if(e.type==='berry'){ellipse(0,4,9,4,'#28594d22');ellipse(-3,0,5,6,'#be614e');ellipse(4,0,5,6,'#ce7255');line(0,-5,3,-9,'#456e46',3);ellipse(3,-8,4,2,'#557b48')}else if(e.type==='bamboo'){ellipse(0,5,29,18,'#e9f6c26b');ctx.rotate(-.4+Math.sin(time*2+e.d)*.08);for(const offset of [-7,7]){line(offset,-23,offset,23,'#47733e',9);line(offset-2,-21,offset-2,21,'#aad478',3);for(const joint of [-12,3,17])line(offset-4,joint,offset+4,joint,'#dbebac',2)}ellipse(15,-18,10,4,'#6b9b4d');ellipse(-15,-6,9,4,'#81ad58');ctx.rotate(.4);text('BOOST',0,-34,9,'#f8f5d9')}else if(e.type==='rock'){ellipse(0,11,31,12,'#e7ebc357');ctx.fillStyle='#778b7c';ctx.beginPath();ctx.moveTo(-26,8);ctx.lineTo(-20,-12);ctx.lineTo(-4,-23);ctx.lineTo(17,-16);ctx.lineTo(28,6);ctx.lineTo(7,16);ctx.closePath();ctx.fill();ctx.fillStyle='#94a393';ctx.beginPath();ctx.moveTo(-20,-12);ctx.lineTo(-4,-23);ctx.lineTo(17,-16);ctx.lineTo(5,-4);ctx.closePath();ctx.fill();line(-20,17,15,19,'#d5e8cc',2)}else{ctx.rotate(.2);line(-40,0,40,0,e.type==='log'?'#886e4e':'#9a8058',e.type==='log'?19:7);line(-30,-4,30,-4,'#b09565',3);if(e.type==='branch')line(5,0,20,-15,'#947c52',5);ellipse(40,0,4,9,'#c1a275')}ctx.restore()}
 for(const dock of mode==='menu'?[{offer:offers[0],target:false,d:3200}]:availableDocks()){const y=sy(dock.d);if(y<-100||y>H+100)continue;const side=dock.target&&dock.offer.branch?dock.offer.branch:dock.offer.side;const x=sx(dockX(dock.offer,dock.target),dock.d);ctx.save();ctx.translate(x,y);ctx.scale(scale,scale);if(mode==='playing'&&dock.d>=run.distance-115){const highlighted=hovered?.offer.id===dock.offer.id&&hovered.target===dock.target;const chosen=selectedDock?.id===dock.offer.id&&selectedDock.target===dock.target;ctx.save();ctx.strokeStyle=highlighted||chosen?'#fff3aa':'#fff6cf70';ctx.fillStyle=highlighted||chosen?'#fff5b526':'#fff5b50a';ctx.lineWidth=highlighted||chosen?2.5:1;ctx.shadowColor='#fff1a1';ctx.shadowBlur=highlighted||chosen?18:0;ctx.setLineDash(highlighted||chosen?[9,7]:[]);ctx.lineDashOffset=-time*16;ctx.beginPath();ctx.ellipse(side*26,-20,55,65,0,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.restore();}for(let j=0;j<5;j++){ctx.fillStyle=j%2?'#c3a273':'#b99869';ctx.fillRect(side<0?-25:0,-30+j*12,27,10)}line(side<0?0:2,-30,side<0?0:2,30,'#8a7354',3);character(side*42,-5,dock.target?dock.offer.recipient:dock.offer.name);ellipse(side*42,-59+Math.sin(time*3)*3,12,14,dock.target?'#d47b42':'#f7edcc');text(dock.target?'✓':'!',side*42,-54+Math.sin(time*3)*3,17,dock.target?'#fff8dd':'#a75a32');text(dock.target?dock.offer.recipient:dock.offer.name,side*42,39,11,'#314f3d');ctx.restore()}
 for(const t of run.active.filter(t=>t.offer.type==='lost')){const y=sy(t.offer.target),x=sx(Math.sin(t.offer.target)*100,t.offer.target);if(y>-80&&y<H+80){ellipse(x,y,22*scale,13*scale,'#eef0c370');text(t.offer.item==='Red scarf'?'〰':'◒',x,y,32*scale,'#b85e3b');text('SPACE',x,y-28*scale,10,'#f8f0d3')}}
 if(vd>FORK.start-1000&&vd<FORK.end+800){const y=sy(FORK.start-180);text('← THE SCENIC ROUTE',sx(-140,FORK.start),y,12*scale,'#31594b');text('RAPIDS →',sx(160,FORK.start),y,12*scale,'#31594b')}
 if(vd>LENGTH-1300){const y=sy(LENGTH);line(sx(-270,LENGTH),y,sx(270,LENGTH),y,'#927247',5*scale);for(let i=-5;i<=5;i++){ctx.fillStyle=i%2?'#bb6947':'#ecd5a2';ctx.beginPath();ctx.moveTo(sx(i*45,LENGTH),y);ctx.lineTo(sx(i*45+20,LENGTH),y+28*scale);ctx.lineTo(sx(i*45+40,LENGTH),y);ctx.fill()}text('FIREFLY CAMP',sx(0,LENGTH),y-30*scale,25*scale,'#faf0cd')}
 panda(mode==='menu'?W*.7:sx(run.x,run.distance),mode==='menu'?H*.56:sy(run.distance),scale*(mode==='menu'?1.7:1));
 if(run.immunity>0&&mode!=='menu'){ctx.strokeStyle=`rgba(250,238,193,${.4+Math.sin(time*12)*.2})`;ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(sx(run.x,run.distance),sy(run.distance),48*scale,66*scale,0,0,Math.PI*2);ctx.stroke()}
 for(const f of floaters)text(f.text,sx(f.x,f.d),sy(f.d)-55-(2-f.life)*15,16*scale,'#fff9d9');
}
function frame(now:number){const dt=Math.min((now-last)/1000,.05);last=now;time+=dt;update(dt);draw();requestAnimationFrame(frame)}
if(!validateContent())throw new Error('Invalid authored task content');requestAnimationFrame(frame);
